### ISSUE TITLE
ValueError: `staleness` option can't be changed while a transaction is in progress

### ISSUE THREAD

**Issue by odino** [googleapis/python-spanner-sqlalchemy#192] opened 2022-01-17 07:23 UTC
#### Environment details

  - OS: Linux `uname -a 5.11.0-46-generic #51~20.04.1-Ubuntu`
  - Language runtime version: Python 3.8.10
  - Package versions:

```
google-cloud-spanner        3.12.1              
sqlalchemy-spanner          1.0.0 
grpc-google-iam-v1          0.12.3              
grpcio                      1.42.0              
grpcio-status               1.42.0              
grpcio-tools                1.38.0 
google-api-client           3.14.159265359.post1
google-api-core             2.3.0               
google-api-python-client    2.0.2               
google-auth                 1.28.0              
google-auth-httplib2        0.1.0               
google-cloud-core           2.2.1               
googleapis-common-protos    1.53.0              
grpc-google-iam-v1          0.12.3
````

#### Steps to reproduce

Running this script:

```py
from sqlalchemy import create_engine

engine = create_engine(
    "spanner:///projects/X/instances/Y/databases/Z"
)

print(engine.execute("SELECT 1").scalar())
```

ends up running the query, but also throwing an error -- output from the CLI:

```
Exception during reset or similar
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 671, in _finalize_fairy
    fairy._reset(pool)
  File "/home/alex/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 847, in _reset
    pool.dispatch.reset(self, self._connection_record)
  File "/home/alex/.local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/home/alex/.local/lib/python3.8/site-packages/google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py", line 51, in reset_connection
    dbapi_conn.connection.staleness = None
  File "/home/alex/.local/lib/python3.8/site-packages/google/cloud/spanner_dbapi/connection.py", line 203, in staleness
    raise ValueError(
ValueError: `staleness` option can't be changed while a transaction is in progress. Commit or rollback the current transaction and try again.
1
```

Now, if I use:

```py
with engine.begin() as connection:
    print(sql(connection, "SELECT 1 + 1").scalar())
```

it's all good. Any idea?

**Comment by IlyaFaer** [comment] 2022-01-17 07:53
@odino, this PR is going to fix the failure: https://github.com/googleapis/python-spanner-sqlalchemy/pull/188/files
Are using the released version?

**Comment by IlyaFaer** [comment] 2022-01-17 07:57
@odino, oh, I guess I know what's happening. By default, you're in `SERIALIZABLE` mode, which means you should commit your operations manually, or use a context manager, like:

```python
with engine.begin() as connection:
    connection.execute(...)
```
Otherwise you're returning a connection back to connections pool, but there is a transaction in progress on the connection.

**Comment by odino** [comment] 2022-01-25 20:49
@IlyaFaer thanks for your pointer -- I do assume that is the problem. Though I see you're working on a PR, as it would be convenient not having to commit / roll it back manually eg. when you're executing just some random selects. I actually did not realize everything ran in the context of a tx here.

**Comment by odino** [comment] 2022-01-25 20:55
BTW one thing to note, when I switch to `AUTOCOMMIT` I still see some funky warning:

```
/home/alex/.local/lib/python3.8/site-packages/google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py:947: UserWarning: This method is non-operational in autocommit mode
  dbapi_connection.rollback()
```

**Comment by vi3k6i5** [comment] 2022-01-28 15:22
The issue is resolved now, will do a release with the fix and update here.

**Comment by vi3k6i5** [comment] 2022-01-28 16:57
The fix is now released with the latest version.

**Comment by kazshinohara** [comment] 2022-02-14 01:33
When v1.1.0 will be available at PyPI ?
https://pypi.org/project/sqlalchemy-spanner/#history

**Comment by larkee** [comment] 2022-02-14 03:56
Hi @kazshinohara,

It looks like the release failed which is why it is not available on PyPI. Unfortunately, the issue for the failure was closed by a bot before we saw it so we weren't aware of this until now. I'm looking into this issue now and will let you know when it has been successfully published to PyPI. 

Apologies for the inconvenience!

**Comment by kazshinohara** [comment] 2022-02-14 18:56
@larkee Thanks !!  I'm planning to talk about this ORM at an user community in Japan next month, hopefully the release wil be landed soon.

**Comment by meetchandan** [comment] 2022-04-21 08:11
hey @vi3k6i5 -- as @kazshinohara mentioned, the v1.1.0 release has failed, any tentative date it woud be released?
We are facing this issue even after using engine.begin()

```
with engine.begin() as connection:
    sql(connection, "SELECT a from b").scalar()
```

**Comment by kazshinohara** [comment] 2022-05-06 13:33
Hi any update on this ?

**Comment by ansh0l** [comment] 2022-05-18 08:02
Hi @asthamohta , please take a look.

**Comment by asthamohta** [comment] 2022-06-02 07:45
Hi @kazshinohara, @IlyaFaer has figured out the issue and will push a solution by tomorrow so hopefully by early next week we will have a release :)

**Comment by IlyaFaer** [comment] 2022-06-06 12:07
I've checked the error on the current `main` branch - everything seems to be in order, no error messages:

![Untitled](https://user-images.githubusercontent.com/26030071/172157098-395f4344-5c70-4c7e-8de8-5a15c20fdd3b.png)

Fixed by #214

Closing the issue. In case the error remains after the next release, feel free to re-open.

**Comment by asthamohta** [comment] 2022-06-09 09:18
Hey @IlyaFaer, the customer is facing the following issues:

The first one is, it seems not to be able to pick up the sqlalchemy-spanner dialect unless I change the database URL from something like this:

"spanner:///projects/project-id/instances/instance-id/databases/database-id"
to this
"spanner+spanner:///projects/project-id/instances/instance-id/databases/database-id"

so, specifying the driver like that fixed the first issue.
and my current database URL setup look like this:

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{PRIMA_DB_USERNAME}:{PRIMA_DB_PASSWORD}@{PRIMA_PROC_DB_HOST}/prima_processing"
SQLALCHEMY_BINDS = {
        "jefe-jobs": "spanner+spanner:///projects/hpc-sandbox-268519/instances/jefe-spanner-instance/databases/jefe-jobs"
    }

The second one is similar to the initial error (not the above one), but this time I get it every time I make a mysql related query it throws this error.

[2022-06-08 10:59:13,949] ERROR in base: Exception during reset or similar
Traceback (most recent call last):
  File "/pdata/devsrc/amhadest/wavepipe-service/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/pdata/devsrc/amhadest/wavepipe-service/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 874, in _reset
    pool.dispatch.reset(self, self._connection_record)
  File "/pdata/devsrc/amhadest/wavepipe-service/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/pdata/devsrc/amhadest/wavepipe-service/venv/lib/python3.8/site-packages/google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py", line 51, in reset_connection
    if dbapi_conn.connection.inside_transaction:
AttributeError: 'Connection' object has no attribute 'inside_transaction'

**Comment by IlyaFaer** [comment] 2022-06-10 11:35
> The second one is similar to the initial error (not the above one), but this time I get it every time I make a mysql related query it throws this error

But, wait, when you create a connection to a Spanner database, SQLAlchemy uses our dialect for all the operations. It's not possible to use this dialect with MySQL, because Spanner and MySQL are different. If I understand your case correctly, you should use two different connections for two different databases - one for Spanner, another one for MySQL. By looking at the database URL prefixes, SQLAlchemy will understand what kind of a connection and dialect should be used. But it must be two separate connections/engines/dialects.

I can add a condition into the reset mechanism not to do anything with no-Spanner connections, but I don't think it'll allow to run MySQL queries on Spanner dialect.

**Comment by amha19** [comment] 2022-06-20 13:09
Apologies for the late response. @IlyaFaer that make sense. It seems the changes made in [this fork ](https://github.com/JoudZouzou/python-spanner-sqlalchemy/commit/a64c3526d69c3f3e86a54fc9bf09457e2456e8cb) and [this change](https://github.com/googleapis/python-spanner-sqlalchemy/pull/222) both can fix the issue I was having even though I’m using a single engine for both Spanner and MySQL (Thank you for that). 
Although the error is gone, if possible, I’m trying to create two different engines and connections, one for Spanner and one for MySQL. The problem is I’m using Flask-SQLAlchemy, and as far as I understand Flask-SQLAlchemy accepts only one SQLALCHEMY_DATABASE_URI and if one need to connect to multiple database, it has to be done through the SQLALCHEMY_BINDS method (as it shown in the code snippet above). 
I understand as it is mentioned in this issue (#221 ), even creating separate engines throws the same error but I thought it would be preferable to have separate engines and connections. So, Is there a way to create separate connections using Flask-sqlalchemy so that they can use different engine and their own dialect?

**Comment by IlyaFaer** [comment] 2022-06-23 07:10
@amha19, if you'll do something like this:

```python
engine = create_engine( "spanner+spanner:///...")
engine2 = create_engine("mysql+mysql:///...") 
```
Engines and connections will be separate (and it's what Flask is doing, as far as I can tell). But all the connections will be using the same reset mechanism. That was the problem of the original issue - connections reset mechanism is global for all the engines and connections on your machine - that's something we didn't expect.

Thus, if I understand correctly what you mean, it's already working like this. Connections are separate, it's the connections reset mechanism which brings confusion because of its globality (but from now on this mechanism first checks what kind of a connection it got before doing the actual reset).

**Closed** 2022-06-24 10:18 UTC
Labels: type: bug, priority: p2, api: spanner
