### ISSUE TITLE
Issue with multiple WHERE clauses

### ISSUE THREAD

**Issue by LeedsDBA** [googleapis/python-spanner-sqlalchemy#183] opened 2021-12-30 19:03 UTC
#### Environment details

  - Programming language: python 3.9.9
  - OS: python:3.9.9-slim-buster image (ubuntu, hosting docker)
  - Language runtime version: 3.9.9
  - Package version: 1.0.0

requirements.txt:
fastapi>=0.68.0,<0.69.0
pydantic>=1.8.0,<2.0.0
uvicorn>=0.15.0
SQLAlchemy>=1.3.23
sqlalchemy-spanner>=1.0.0 

#### Steps to reproduce
>> Not causing me an issue now, but raising in case anyone wants to investigate.

I'm getting the error message:
TypeError: where() takes 2 positional arguments but 3 were given.

Steps to reproduce:
0. create ds_table in Spanner:

CREATE TABLE ds_table (
  ds_id STRING(10) NOT NULL,
  product_id INT64 NOT NULL,
  flight_number STRING(5) NOT NULL,
  departure_datetime TIMESTAMP NOT NULL,
  price NUMERIC,
) PRIMARY KEY(ds_id);

  1. dockerfile:
# syntax=docker/dockerfile:1
FROM python:3.9.9-slim-buster
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . ./app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
EXPOSE 8000

  2. main.py
from datetime import date
from sqlalchemy import MetaData, Table, create_engine, select
from sqlalchemy.sql.sqltypes import DateTime
from fastapi import FastAPI, HTTPException
from typing import Optional
from fastapi.responses import JSONResponse

engine = create_engine(
    "spanner:///projects/OMMITTED/instances/OMMITTED/databases/OMITTED"
)

app = FastAPI()

table = Table("ds_table", MetaData(bind=engine), autoload=True)

#def get_data(flight_id str, departure_datetime str, product_id int):
#    return 0

@app.get("/flight/{flight_number}/product/{product_id}")
def read_data(flight_number:str, product_id:int):
    with engine.begin() as connection:
        return connection.execute(select(["*"], from_obj=table).**where(table.c.flight_number==flight_number, table.c.product_id==product_id)**.limit(10)).fetchall()

4. Run docker image passing in JSON credentials as a volume mount\

#### Workarounds:
I can change the WHERE clause to be separate calls and it works:

connection.execute(select(["*"], from_obj=table)**.where(table.c.flight_number==flight_number).where(table.c.product_id==product_id)**.limit(10)).fetchall()

**Comment by IlyaFaer** [comment] 2022-01-06 08:18
@LeedsDBA, thanks for the detailed issue report!

My guess is that this problem is related to SQLAlchemy syntax, not to the Spanner dialect. As far as I understand, you want to execute a complex WHERE clause, with AND and OR operators. In this case you should use `and_()` and `or_()` functions of SQLAlchemy, for example:

```python
from sqlalchemy import (MetaData, Table, and_)

metadata = MetaData()

visitors = Table('visitors', metadata, ...)

update = (
    visitors.update()
    .where(and_(visitors.c.product_id == product_id,
                visitors.c.date == day))
)

connection.execute(update)
```
See the WHERE clause related docs page for more details:
https://docs.sqlalchemy.org/en/14/core/selectable.html#sqlalchemy.sql.expression.Select.where

**Comment by IlyaFaer** [comment] 2022-01-13 07:22
I assume the problem causes has been figured out. Closing.
Feel free to reopen in case the issue isn't resolved.

**Closed by IlyaFaer** 2022-01-13 07:22 UTC
Labels: type: question, priority: p2, api: spanner
